spring.application.name=S7SpringCRUD
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-classname=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
